# Basic dependabot.yml file with

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: 'daily'
      time: '02:00'
    # Raise all npm pull requests with custom labels
    labels:
      - 'npm dependencies'
      - 'triage-board'
    allow:
      # Allow updates for All
      - dependency-name: '*'
      # Allow updates for any packages starting "@storybook"
      - dependency-name: '@storybook*'
    # Allow up to 10 open pull requests for pip dependencies
    open-pull-requests-limit: 10

  # Configuration for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    ignore:
      # Ignore updates to packages that start with 'aws'
      # Wildcards match zero or more arbitrary characters
      - dependency-name: 'aws*'
      # Ignore some updates to the 'express' package
      - dependency-name: 'express'
        # Ignore only new versions for 4.x and 5.x
        versions: ['4.x', '5.x']
      # For all packages, ignore all patch updates
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
